### PR TITLE
imx8mq-evk: add serial and timer support

### PR DESCRIPTION
**Pull request by pingerino**
Add required files for imx8mq-evk to use the SerialServer and
TimerServer.

### CODE REVIEW

**Comment by nomadeel** [comment]
Sorry for the late response. The PR looks good and is ready to be pulled in, but can you wait a little longer? I'm working on some stuff that'll get rid of the platform files for the TimeServer.

**Comment by pingerino** [comment]
@nomadeel sounds awesome!

**Comment by nomadeel** [comment]
@pingerino I've added the new changes now. Can you rework the commit to remove this file:  `components/TimeServer/src/plat/imx8mq-evk/plat.c`?

**Comment by pingerino** [comment]
Done!

**Comment by nomadeel** [comment]
Cool, I'll pull in the patches now. Won't be long.

**Comment by kent-mcleod** [comment]
This was done in c9edbb11c51689076f0d8243e5418747725f62d1

**Pull request closed without merging**
