### PR TITLE
CMake: split CMake file

### PR DESCRIPTION
**Pull request by axel-h**
Split the CMake file into two files, one for the component and one for the connectors. This allows using just the connectors in projects without being forced to use the components also.

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 2aa77f9bbbbd63727a2fc322e68dea9d7c3c3dc7

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - global-components - EXT-axel-h-patch-axel-1-15 | SUCCESSFUL |
| Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-15 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-15 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    23-Oct-2020 10:11:09	Build Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-15 - style #1 (CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR-1) started building on agent A local agent 1
    23-Oct-2020 10:11:09	I run on the Bamboo server!
    23-Oct-2020 10:11:09	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR
    23-Oct-2020 10:11:09	Executing build Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-15 - style #1 (CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR-1)
    23-Oct-2020 10:11:09	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR/. (location: .)
    23-Oct-2020 10:11:09	Artifact 'code' prepared in 17.77 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR/./code.tar.gz
    23-Oct-2020 10:11:09	Running pre-build action: VCS Version Collector
    23-Oct-2020 10:11:09	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Oct-2020 10:11:09	+ tar xf code.tar.gz --recursive-unlink
    23-Oct-2020 10:11:09	Finished task 'Untar code' with result: Success
    23-Oct-2020 10:11:09	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Oct-2020 10:11:09	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR
    23-Oct-2020 10:11:09	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    23-Oct-2020 10:11:09	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Oct-2020 10:11:09	+ cd global-components
    23-Oct-2020 10:11:09	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR/seL4_tools/misc/style.sh
    23-Oct-2020 10:11:09	++ git merge-base 2aa77f9bbbbd63727a2fc322e68dea9d7c3c3dc7 876d8eb8a3a27421f70a150160f33a793d1098bd
    23-Oct-2020 10:11:09	+ git diff --name-only 2aa77f9bbbbd63727a2fc322e68dea9d7c3c3dc7 876d8eb8a3a27421f70a150160f33a793d1098bd
    23-Oct-2020 10:11:10	+ git diff --exit-code
    23-Oct-2020 10:11:10	diff --git a/global-components.cmake b/global-components.cmake
    23-Oct-2020 10:11:10	index d2ebe09..6cd63ec 100644
    23-Oct-2020 10:11:10	--- a/global-components.cmake
    23-Oct-2020 10:11:10	+++ b/global-components.cmake
    23-Oct-2020 10:11:10	@@ -14,10 +14,7 @@ cmake_minimum_required(VERSION 3.8.2)
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	 include("${CMAKE_CURRENT_LIST_DIR}/global-connectors.cmake")
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	-CAmkESAddImportPath(
    23-Oct-2020 10:11:10	-    components
    23-Oct-2020 10:11:10	-    plat_components/${KernelPlatform}
    23-Oct-2020 10:11:10	-)
    23-Oct-2020 10:11:10	+CAmkESAddImportPath(components plat_components/${KernelPlatform})
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	 foreach(
    23-Oct-2020 10:11:10	     comp
    23-Oct-2020 10:11:10	diff --git a/global-connectors.cmake b/global-connectors.cmake
    23-Oct-2020 10:11:10	index 69668f1..b86e3ba 100644
    23-Oct-2020 10:11:10	--- a/global-connectors.cmake
    23-Oct-2020 10:11:10	+++ b/global-connectors.cmake
    23-Oct-2020 10:11:10	@@ -12,10 +12,7 @@
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	 cmake_minimum_required(VERSION 3.8.2)
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	-CAmkESAddImportPath(
    23-Oct-2020 10:11:10	-    interfaces
    23-Oct-2020 10:11:10	-    plat_interfaces/${KernelPlatform}
    23-Oct-2020 10:11:10	-)
    23-Oct-2020 10:11:10	+CAmkESAddImportPath(interfaces plat_interfaces/${KernelPlatform})
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	 CAmkESAddTemplatesPath(templates)
    23-Oct-2020 10:11:10	 
    23-Oct-2020 10:11:10	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR-1-ScriptBuildTask-6807232092876788742.sh] was 1 while expected 0
    23-Oct-2020 10:11:10	Finished task 'Check style of changed files' with result: Failed
    23-Oct-2020 10:11:10	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Oct-2020 10:11:10	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR
    23-Oct-2020 10:11:10	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    23-Oct-2020 10:11:10	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Oct-2020 10:11:10	+ cd global-components
    23-Oct-2020 10:11:10	++ echo ssh://git@bitbucket.keg.ertos.in.nicta.com.au:7999/sel4proj/global-components.git
    23-Oct-2020 10:11:10	++ cut -d/ -f4
    23-Oct-2020 10:11:10	+ bb_proj=sel4proj
    23-Oct-2020 10:11:10	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4proj global-components
    23-Oct-2020 10:11:10	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    23-Oct-2020 10:11:10	+ SCRIPT_DIR=/scripts/bb_code_insights
    23-Oct-2020 10:11:10	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    23-Oct-2020 10:11:10	+ BBS_PROJECT=sel4proj
    23-Oct-2020 10:11:10	+ BBS_REPO=global-components
    23-Oct-2020 10:11:10	+ REPORT_TO_RUN=astyle
    23-Oct-2020 10:11:10	++ git rev-parse HEAD
    23-Oct-2020 10:11:10	+ COMMIT_ID=2aa77f9bbbbd63727a2fc322e68dea9d7c3c3dc7
    23-Oct-2020 10:11:10	+ REPORT_KEY=astyle.report
    23-Oct-2020 10:11:10	+ set +x
    23-Oct-2020 10:11:10	+ report_file=astyle_report.json
    23-Oct-2020 10:11:10	+ annotations_file=astyle_annotations.json
    23-Oct-2020 10:11:10	+ rm -f astyle_report.json astyle_annotations.json
    23-Oct-2020 10:11:10	+ /scripts/bb_code_insights/astyle
    23-Oct-2020 10:11:12	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    23-Oct-2020 10:11:12	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    23-Oct-2020 10:11:12	+ set +x
    23-Oct-2020 10:11:12	+ '[' -f astyle_report.json ']'
    23-Oct-2020 10:11:12	+ cat astyle_report.json
    23-Oct-2020 10:11:12	+ '[' -f astyle_annotations.json ']'
    23-Oct-2020 10:11:12	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1603408272518,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    23-Oct-2020 10:11:12	Finished task 'Run astyle code insights' with result: Success
    23-Oct-2020 10:11:12	Running post build plugin 'NCover Results Collector'
    23-Oct-2020 10:11:12	Running post build plugin 'Artifact Copier'
    23-Oct-2020 10:11:12	Running post build plugin 'npm Cache Cleanup'
    23-Oct-2020 10:11:12	Running post build plugin 'Clover Results Collector'
    23-Oct-2020 10:11:12	Running post build plugin 'Docker Container Cleanup'
    23-Oct-2020 10:11:12	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR'
    23-Oct-2020 10:11:12	Finalising the build...
    23-Oct-2020 10:11:12	Stopping timer.
    23-Oct-2020 10:11:12	Build CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR-1 completed.
    23-Oct-2020 10:11:12	Running on server: post build plugin 'NCover Results Collector'
    23-Oct-2020 10:11:12	Running on server: post build plugin 'Build Hanging Detection Configuration'
    23-Oct-2020 10:11:12	Running on server: post build plugin 'Clover Delta Calculator'
    23-Oct-2020 10:11:12	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    23-Oct-2020 10:11:12	All post build plugins have finished
    23-Oct-2020 10:11:12	Generating build results summary...
    23-Oct-2020 10:11:12	Saving build results to disk...
    23-Oct-2020 10:11:12	Store variable context...
    23-Oct-2020 10:11:12	Indexing build results...
    23-Oct-2020 10:11:12	Finished building CQ-GLOBALCOMPONENTSSTYLE112-GLOBALCOMPONENTSSTYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
