### PR TITLE
Improve maintainability

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 5424a37454bc42f3a099a6e69091498faeabdd77

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - global-components - EXT-axel-h-patch-axel-1-11 | SUCCESSFUL |
| Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-11 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-11 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    18-Oct-2020 09:30:49	Build Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-11 - style #1 (CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR-1) started building on agent A local agent 1
    18-Oct-2020 09:30:49	I run on the Bamboo server!
    18-Oct-2020 09:30:49	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR
    18-Oct-2020 09:30:49	Executing build Code Quality - Style - global-components - EXT-axel-h-patch-axel-1-11 - style #1 (CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR-1)
    18-Oct-2020 09:30:49	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR/. (location: .)
    18-Oct-2020 09:30:49	Artifact 'code' prepared in 31.22 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR/./code.tar.gz
    18-Oct-2020 09:30:49	Running pre-build action: VCS Version Collector
    18-Oct-2020 09:30:49	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 09:30:49	+ tar xf code.tar.gz --recursive-unlink
    18-Oct-2020 09:30:49	Finished task 'Untar code' with result: Success
    18-Oct-2020 09:30:49	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 09:30:49	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR
    18-Oct-2020 09:30:49	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    18-Oct-2020 09:30:49	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 09:30:49	+ cd global-components
    18-Oct-2020 09:30:49	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR/seL4_tools/misc/style.sh
    18-Oct-2020 09:30:49	++ git merge-base 5424a37454bc42f3a099a6e69091498faeabdd77 37620714be9c72fdaa9a0d7f116f04c1fe08a7dd
    18-Oct-2020 09:30:49	+ git diff --name-only 5424a37454bc42f3a099a6e69091498faeabdd77 37620714be9c72fdaa9a0d7f116f04c1fe08a7dd
    18-Oct-2020 09:30:51	+ git diff --exit-code
    18-Oct-2020 09:30:51	diff --git a/global-components.cmake b/global-components.cmake
    18-Oct-2020 09:30:51	index 8b600d0..d962ac2 100644
    18-Oct-2020 09:30:51	--- a/global-components.cmake
    18-Oct-2020 09:30:51	+++ b/global-components.cmake
    18-Oct-2020 09:30:51	@@ -23,116 +23,148 @@ CAmkESAddTemplatesPath(templates)
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 foreach(
    18-Oct-2020 09:30:51	     comp
    18-Oct-2020 09:30:51	-    IN ITEMS
    18-Oct-2020 09:30:51	-        remote-drivers/picotcp-ethernet-async
    18-Oct-2020 09:30:51	-        remote-drivers/picotcp-socket-sync
    18-Oct-2020 09:30:51	-        components/modules/fdt-bind-driver
    18-Oct-2020 09:30:51	-        components/modules/dynamic-untyped-allocators
    18-Oct-2020 09:30:51	-        components/modules/single-threaded
    18-Oct-2020 09:30:51	-        components/modules/x86-iospace-dma
    18-Oct-2020 09:30:51	-        components/modules/picotcp-base
    18-Oct-2020 09:30:51	-        components/ClockServer
    18-Oct-2020 09:30:51	-        components/GPIOMUXServer
    18-Oct-2020 09:30:51	-        components/ResetServer
    18-Oct-2020 09:30:51	-        plat_components/tx2/BPMPServer
    18-Oct-2020 09:30:51	+    IN
    18-Oct-2020 09:30:51	+    ITEMS
    18-Oct-2020 09:30:51	+    remote-drivers/picotcp-ethernet-async
    18-Oct-2020 09:30:51	+    remote-drivers/picotcp-socket-sync
    18-Oct-2020 09:30:51	+    components/modules/fdt-bind-driver
    18-Oct-2020 09:30:51	+    components/modules/dynamic-untyped-allocators
    18-Oct-2020 09:30:51	+    components/modules/single-threaded
    18-Oct-2020 09:30:51	+    components/modules/x86-iospace-dma
    18-Oct-2020 09:30:51	+    components/modules/picotcp-base
    18-Oct-2020 09:30:51	+    components/ClockServer
    18-Oct-2020 09:30:51	+    components/GPIOMUXServer
    18-Oct-2020 09:30:51	+    components/ResetServer
    18-Oct-2020 09:30:51	+    plat_components/tx2/BPMPServer
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	     add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/${comp}" ${comp})
    18-Oct-2020 09:30:51	 endforeach()
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 foreach(
    18-Oct-2020 09:30:51	     comp
    18-Oct-2020 09:30:51	-    IN ITEMS
    18-Oct-2020 09:30:51	-        PCIConfigIO
    18-Oct-2020 09:30:51	-        RTC
    18-Oct-2020 09:30:51	-        SerialServer
    18-Oct-2020 09:30:51	-        TimeServer
    18-Oct-2020 09:30:51	-        FileServer
    18-Oct-2020 09:30:51	-        VirtQueue
    18-Oct-2020 09:30:51	-        BenchUtiliz
    18-Oct-2020 09:30:51	-        Ethdriver
    18-Oct-2020 09:30:51	-        PicoServer
    18-Oct-2020 09:30:51	+    IN
    18-Oct-2020 09:30:51	+    ITEMS
    18-Oct-2020 09:30:51	+    PCIConfigIO
    18-Oct-2020 09:30:51	+    RTC
    18-Oct-2020 09:30:51	+    SerialServer
    18-Oct-2020 09:30:51	+    TimeServer
    18-Oct-2020 09:30:51	+    FileServer
    18-Oct-2020 09:30:51	+    VirtQueue
    18-Oct-2020 09:30:51	+    BenchUtiliz
    18-Oct-2020 09:30:51	+    Ethdriver
    18-Oct-2020 09:30:51	+    PicoServer
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	     include("${CMAKE_CURRENT_LIST_DIR}/components/${comp}/CMakeLists.txt")
    18-Oct-2020 09:30:51	 endforeach()
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 foreach(
    18-Oct-2020 09:30:51	     connector
    18-Oct-2020 09:30:51	-    IN ITEMS
    18-Oct-2020 09:30:51	-        seL4RPCDataportSignal
    18-Oct-2020 09:30:51	-        seL4GlobalAsynch
    18-Oct-2020 09:30:51	-        seL4GlobalAsynchCallback
    18-Oct-2020 09:30:51	-        seL4Ethdriver
    18-Oct-2020 09:30:51	-        seL4MessageQueue
    18-Oct-2020 09:30:51	-        seL4RPCOverMultiSharedData
    18-Oct-2020 09:30:51	+    IN
    18-Oct-2020 09:30:51	+    ITEMS
    18-Oct-2020 09:30:51	+    seL4RPCDataportSignal
    18-Oct-2020 09:30:51	+    seL4GlobalAsynch
    18-Oct-2020 09:30:51	+    seL4GlobalAsynchCallback
    18-Oct-2020 09:30:51	+    seL4Ethdriver
    18-Oct-2020 09:30:51	+    seL4MessageQueue
    18-Oct-2020 09:30:51	+    seL4RPCOverMultiSharedData
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	     DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	         ${connector}
    18-Oct-2020 09:30:51	-        FROM ${connector}-from.template.c
    18-Oct-2020 09:30:51	-        TO ${connector}-to.template.c
    18-Oct-2020 09:30:51	+        FROM
    18-Oct-2020 09:30:51	+        ${connector}-from.template.c
    18-Oct-2020 09:30:51	+        TO
    18-Oct-2020 09:30:51	+        ${connector}-to.template.c
    18-Oct-2020 09:30:51	     )
    18-Oct-2020 09:30:51	 endforeach()
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4SharedDataWithCaps
    18-Oct-2020 09:30:51	-    FROM seL4SharedDataWithCaps.template.c
    18-Oct-2020 09:30:51	-    TO seL4SharedDataWithCaps.template.c
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4SharedDataWithCaps.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4SharedDataWithCaps.template.c
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4TimeServer
    18-Oct-2020 09:30:51	-    FROM seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	-    FROM_HEADER get-notification.template.h
    18-Oct-2020 09:30:51	-    TO seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	+    FROM_HEADER
    18-Oct-2020 09:30:51	+    get-notification.template.h
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4SerialServer
    18-Oct-2020 09:30:51	-    FROM seL4RPCDataportSignal-from.template.c
    18-Oct-2020 09:30:51	-    FROM_HEADER get-notification.template.h
    18-Oct-2020 09:30:51	-    TO seL4RPCDataportSignal-to.template.c
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCDataportSignal-from.template.c
    18-Oct-2020 09:30:51	+    FROM_HEADER
    18-Oct-2020 09:30:51	+    get-notification.template.h
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCDataportSignal-to.template.c
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4RPCCallSignal
    18-Oct-2020 09:30:51	-    FROM seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCCallSignal-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4RPCCallSignalNoThreads
    18-Oct-2020 09:30:51	-    FROM seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCCallSignal-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4PicoServerSignal
    18-Oct-2020 09:30:51	-    FROM seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	-    FROM_HEADER get-notification.template.h
    18-Oct-2020 09:30:51	-    TO seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCCallSignal-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-from.template.c
    18-Oct-2020 09:30:51	+    FROM_HEADER
    18-Oct-2020 09:30:51	+    get-notification.template.h
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCCallSignal-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4RPCDataport
    18-Oct-2020 09:30:51	-    FROM seL4RPCDataport-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4RPCDataport-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCDataport-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCDataport-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCDataport-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCDataport-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4RPCDataportNoThreads
    18-Oct-2020 09:30:51	-    FROM seL4RPCDataport-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4RPCDataport-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCDataport-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCDataport-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCDataport-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCDataport-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4PicoServer
    18-Oct-2020 09:30:51	-    FROM seL4RPCDataport-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4RPCDataport-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCDataport-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCDataport-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCDataport-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCDataport-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	@@ -141,30 +173,42 @@ DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4RPCNoThreads
    18-Oct-2020 09:30:51	-    FROM seL4RPCNoThreads-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4RPCNoThreads-to.template.c
    18-Oct-2020 09:30:51	-    TO_HEADER seL4RPCNoThreads-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4RPCNoThreads-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4RPCNoThreads-to.template.c
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4RPCNoThreads-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4DTBHardwareThreadless
    18-Oct-2020 09:30:51	-    FROM empty.c
    18-Oct-2020 09:30:51	-    TO seL4DTBHardwareThreadless.template.c
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    empty.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4DTBHardwareThreadless.template.c
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(seL4DTBHWThreadless TO seL4DTBHardwareThreadless.template.c)
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4VirtQueues
    18-Oct-2020 09:30:51	-    FROM seL4VirtQueues-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4VirtQueues-to.template.c
    18-Oct-2020 09:30:51	-    FROM_HEADER seL4VirtQueues-from.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4VirtQueues-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4VirtQueues-to.template.c
    18-Oct-2020 09:30:51	+    FROM_HEADER
    18-Oct-2020 09:30:51	+    seL4VirtQueues-from.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	 
    18-Oct-2020 09:30:51	 DeclareCAmkESConnector(
    18-Oct-2020 09:30:51	     seL4GPIOServer
    18-Oct-2020 09:30:51	-    FROM seL4GPIOServer-from.template.c
    18-Oct-2020 09:30:51	-    TO seL4GPIOServer-to.template.c
    18-Oct-2020 09:30:51	-    FROM_HEADER seL4GPIOServer-from.template.h
    18-Oct-2020 09:30:51	-    TO_HEADER seL4GPIOServer-to.template.h
    18-Oct-2020 09:30:51	+    FROM
    18-Oct-2020 09:30:51	+    seL4GPIOServer-from.template.c
    18-Oct-2020 09:30:51	+    TO
    18-Oct-2020 09:30:51	+    seL4GPIOServer-to.template.c
    18-Oct-2020 09:30:51	+    FROM_HEADER
    18-Oct-2020 09:30:51	+    seL4GPIOServer-from.template.h
    18-Oct-2020 09:30:51	+    TO_HEADER
    18-Oct-2020 09:30:51	+    seL4GPIOServer-to.template.h
    18-Oct-2020 09:30:51	 )
    18-Oct-2020 09:30:51	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR-1-ScriptBuildTask-2242078185553944420.sh] was 1 while expected 0
    18-Oct-2020 09:30:51	Finished task 'Check style of changed files' with result: Failed
    18-Oct-2020 09:30:51	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 09:30:51	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR
    18-Oct-2020 09:30:51	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    18-Oct-2020 09:30:51	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 09:30:51	+ cd global-components
    18-Oct-2020 09:30:51	++ echo ssh://git@bitbucket.keg.ertos.in.nicta.com.au:7999/sel4proj/global-components.git
    18-Oct-2020 09:30:51	++ cut -d/ -f4
    18-Oct-2020 09:30:51	+ bb_proj=sel4proj
    18-Oct-2020 09:30:51	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4proj global-components
    18-Oct-2020 09:30:51	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    18-Oct-2020 09:30:51	+ SCRIPT_DIR=/scripts/bb_code_insights
    18-Oct-2020 09:30:51	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    18-Oct-2020 09:30:51	+ BBS_PROJECT=sel4proj
    18-Oct-2020 09:30:51	+ BBS_REPO=global-components
    18-Oct-2020 09:30:51	+ REPORT_TO_RUN=astyle
    18-Oct-2020 09:30:51	++ git rev-parse HEAD
    18-Oct-2020 09:30:51	+ COMMIT_ID=5424a37454bc42f3a099a6e69091498faeabdd77
    18-Oct-2020 09:30:51	+ REPORT_KEY=astyle.report
    18-Oct-2020 09:30:51	+ set +x
    18-Oct-2020 09:30:51	+ report_file=astyle_report.json
    18-Oct-2020 09:30:51	+ annotations_file=astyle_annotations.json
    18-Oct-2020 09:30:51	+ rm -f astyle_report.json astyle_annotations.json
    18-Oct-2020 09:30:51	+ /scripts/bb_code_insights/astyle
    18-Oct-2020 09:30:53	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    18-Oct-2020 09:30:53	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    18-Oct-2020 09:30:53	+ set +x
    18-Oct-2020 09:30:53	+ '[' -f astyle_report.json ']'
    18-Oct-2020 09:30:53	+ cat astyle_report.json
    18-Oct-2020 09:30:53	+ '[' -f astyle_annotations.json ']'
    18-Oct-2020 09:30:53	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1602973853527,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    18-Oct-2020 09:30:53	Finished task 'Run astyle code insights' with result: Success
    18-Oct-2020 09:30:53	Running post build plugin 'NCover Results Collector'
    18-Oct-2020 09:30:53	Running post build plugin 'Artifact Copier'
    18-Oct-2020 09:30:53	Running post build plugin 'npm Cache Cleanup'
    18-Oct-2020 09:30:53	Running post build plugin 'Clover Results Collector'
    18-Oct-2020 09:30:53	Running post build plugin 'Docker Container Cleanup'
    18-Oct-2020 09:30:53	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR'
    18-Oct-2020 09:30:53	Finalising the build...
    18-Oct-2020 09:30:53	Stopping timer.
    18-Oct-2020 09:30:53	Build CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR-1 completed.
    18-Oct-2020 09:30:53	Running on server: post build plugin 'NCover Results Collector'
    18-Oct-2020 09:30:53	Running on server: post build plugin 'Build Hanging Detection Configuration'
    18-Oct-2020 09:30:53	Running on server: post build plugin 'Clover Delta Calculator'
    18-Oct-2020 09:30:53	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    18-Oct-2020 09:30:53	All post build plugins have finished
    18-Oct-2020 09:30:53	Generating build results summary...
    18-Oct-2020 09:30:53	Saving build results to disk...
    18-Oct-2020 09:30:53	Store variable context...
    18-Oct-2020 09:30:53	Indexing build results...
    18-Oct-2020 09:30:53	Finished building CQ-GLOBALCOMPONENTSSTYLE109-GLOBALCOMPONENTSSTYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by axel-h** [comment]
dropping the formatting commit, as (again) the formatter is not smart enough to honor nicely looking code.

**Pull request merged**
