### PR TITLE
Zcu102

### PR DESCRIPTION
**Pull request by chrisguikema**
These commits add serial and time server support for the zcu102. Without the util libs commits, the time server will work for ~38 seconds, and the serial server will function, but the interrupt will never actually be cleared in hardware. 

I also added a couple bug fix commits and remove some failed assertions and fix the output colors.

### CODE REVIEW

**Comment by nomadeel** [comment]
Everything looks good, but can you wait a little longer for the patches to be pulled in? I'm working on some stuff that'll remove the need for platform specific code for zcu102 for the TimeServer.

**Comment by chrisguikema** [comment]
Sounds good.

**Comment by nomadeel** [comment]
@chrisguikema I've added the new changes. Can you rework commit 758f7e152b13c797e7baba38159c2aa34a4f00ee to remove `components/TimeServer/src/plat/zynqmp/plat.c`?

Also, for commit f4d17d1948e2c67be151dd631b5568ab4d647a44, can you elaborate a bit more about the problem you are trying to fix? I've tested this PR without that commit and there doesn't seem to be an issue with our tests.

**Comment by chrisguikema** [comment]
Sure. I removed that commit from our zynqmp camkes-arm-vm system, and this is the terminal output pre-vmm:

```AssAesrsteirotni ofna iflaeidl:e d!:" u!n"ruenarcehaacbhlaeb"l e("v m(1v/mf0s/_fsse_Ls4eRLP4CRDP£ÁÑ½ÉÁ?}Ét._c0:. cf:s _f_sr_u_nr:u n4:4 14)4
1)
camkes_virtqueue_device_init@virtqueue.c:129 Failed to get channel
virtqueue_init@server_virtqueue.c:191 Unable to initialise serial server read virtqueue
camkes_virtqueue_device_init@virtqueue.c:129 Failed to get channel
virtqueue_init@server_virtqueue.c:196 Unable to initialise serial server write virtqueue
post_init@serial.c:535 Serial server does not support read and write virtqueues```

**Comment by nomadeel** [comment]
Ah ok, I see what's wrong now. I'll bring your patches in now.

**Pull request merged**
