### PR TITLE
templates: move empty.c to generic templates

### PR DESCRIPTION
**Pull request by axel-h**
`seL4DTBHardwareThreadless` uses the empty template `empty.c`, so it should not be in `remote-drivers/picotcp-ethernet-async/templates` but in `templates`. Then it's more straig forward that `global-components.cmake` contains the line 
`CAmkESAddTemplatesPath(templates)` and that provides all that is needed for this file to work on it's own - or a clone like in my case, an that I how I ran into this issue.

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Review by kent-mcleod — APPROVED** [review]
I wonder if eventually camkes will need some sort of template name-spacing mechanism or a per termplate include path.

**Pull request merged**
