### PR TITLE
BenchUtiliz: guard availability

### PR DESCRIPTION
**Pull request by axel-h**
Fix for https://github.com/SEL4PROJ/global-components/issues/12

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo test

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit e5ca11e8ca8a97337ef7ee17e5318c188c40dd2d

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - global-components - EXT-axel-h-patch-axel-3-13 | SUCCESSFUL |
| Code Quality - Style - global-components - EXT-axel-h-patch-axel-3-13 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - global-components - EXT-axel-h-patch-axel-3-13 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    18-Oct-2020 10:47:43	Build Code Quality - Style - global-components - EXT-axel-h-patch-axel-3-13 - style #1 (CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR-1) started building on agent A local agent 2
    18-Oct-2020 10:47:43	I run on the Bamboo server!
    18-Oct-2020 10:47:43	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR
    18-Oct-2020 10:47:43	Executing build Code Quality - Style - global-components - EXT-axel-h-patch-axel-3-13 - style #1 (CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR-1)
    18-Oct-2020 10:47:43	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR/. (location: .)
    18-Oct-2020 10:47:43	Artifact 'code' prepared in 26.22 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR/./code.tar.gz
    18-Oct-2020 10:47:43	Running pre-build action: VCS Version Collector
    18-Oct-2020 10:47:43	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 10:47:43	+ tar xf code.tar.gz --recursive-unlink
    18-Oct-2020 10:47:43	Finished task 'Untar code' with result: Success
    18-Oct-2020 10:47:43	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 10:47:43	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR
    18-Oct-2020 10:47:43	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    18-Oct-2020 10:47:43	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 10:47:43	+ cd global-components
    18-Oct-2020 10:47:43	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR/seL4_tools/misc/style.sh
    18-Oct-2020 10:47:43	++ git merge-base e5ca11e8ca8a97337ef7ee17e5318c188c40dd2d 37620714be9c72fdaa9a0d7f116f04c1fe08a7dd
    18-Oct-2020 10:47:43	+ git diff --name-only e5ca11e8ca8a97337ef7ee17e5318c188c40dd2d 37620714be9c72fdaa9a0d7f116f04c1fe08a7dd
    18-Oct-2020 10:47:44	+ git diff --exit-code
    18-Oct-2020 10:47:44	diff --git a/components/BenchUtiliz/CMakeLists.txt b/components/BenchUtiliz/CMakeLists.txt
    18-Oct-2020 10:47:44	index f352f2f..4b48882 100644
    18-Oct-2020 10:47:44	--- a/components/BenchUtiliz/CMakeLists.txt
    18-Oct-2020 10:47:44	+++ b/components/BenchUtiliz/CMakeLists.txt
    18-Oct-2020 10:47:44	@@ -12,7 +12,6 @@
    18-Oct-2020 10:47:44	 
    18-Oct-2020 10:47:44	 cmake_minimum_required(VERSION 3.8.2)
    18-Oct-2020 10:47:44	 
    18-Oct-2020 10:47:44	-
    18-Oct-2020 10:47:44	 if(KernelArchARM AND NOT KernelArmExportPMUUser)
    18-Oct-2020 10:47:44	     message("BenchUtiliz not available, as KernelArmExportPMUUser is OFF")
    18-Oct-2020 10:47:44	     return()
    18-Oct-2020 10:47:44	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR-1-ScriptBuildTask-9097749820715912036.sh] was 1 while expected 0
    18-Oct-2020 10:47:44	Finished task 'Check style of changed files' with result: Failed
    18-Oct-2020 10:47:44	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 10:47:44	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR
    18-Oct-2020 10:47:44	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    18-Oct-2020 10:47:44	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    18-Oct-2020 10:47:44	+ cd global-components
    18-Oct-2020 10:47:44	++ echo ssh://git@bitbucket.keg.ertos.in.nicta.com.au:7999/sel4proj/global-components.git
    18-Oct-2020 10:47:44	++ cut -d/ -f4
    18-Oct-2020 10:47:44	+ bb_proj=sel4proj
    18-Oct-2020 10:47:44	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4proj global-components
    18-Oct-2020 10:47:44	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    18-Oct-2020 10:47:44	+ SCRIPT_DIR=/scripts/bb_code_insights
    18-Oct-2020 10:47:44	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    18-Oct-2020 10:47:44	+ BBS_PROJECT=sel4proj
    18-Oct-2020 10:47:44	+ BBS_REPO=global-components
    18-Oct-2020 10:47:44	+ REPORT_TO_RUN=astyle
    18-Oct-2020 10:47:44	++ git rev-parse HEAD
    18-Oct-2020 10:47:44	+ COMMIT_ID=e5ca11e8ca8a97337ef7ee17e5318c188c40dd2d
    18-Oct-2020 10:47:44	+ REPORT_KEY=astyle.report
    18-Oct-2020 10:47:44	+ set +x
    18-Oct-2020 10:47:44	+ report_file=astyle_report.json
    18-Oct-2020 10:47:44	+ annotations_file=astyle_annotations.json
    18-Oct-2020 10:47:44	+ rm -f astyle_report.json astyle_annotations.json
    18-Oct-2020 10:47:44	+ /scripts/bb_code_insights/astyle
    18-Oct-2020 10:47:46	Reporting on these files:  ['components/BenchUtiliz/CMakeLists.txt']
    18-Oct-2020 10:47:46	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    18-Oct-2020 10:47:46	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    18-Oct-2020 10:47:46	+ set +x
    18-Oct-2020 10:47:47	+ '[' -f astyle_report.json ']'
    18-Oct-2020 10:47:47	+ cat astyle_report.json
    18-Oct-2020 10:47:47	+ '[' -f astyle_annotations.json ']'
    18-Oct-2020 10:47:47	+ cat astyle_annotations.json
    18-Oct-2020 10:47:47	{"data":[{"title":"Total number of files with incorrect style","value":1},{"title":"Total number of lines with incorrect style","value":1}],"createdDate":1602978467134,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 1}, {"title": "Total number of lines with incorrect style", "value": 1}]}{"annotations": [{"path": "components/BenchUtiliz/CMakeLists.txt", "line": 15, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}]}
    18-Oct-2020 10:47:47	Finished task 'Run astyle code insights' with result: Success
    18-Oct-2020 10:47:47	Running post build plugin 'NCover Results Collector'
    18-Oct-2020 10:47:47	Running post build plugin 'Artifact Copier'
    18-Oct-2020 10:47:47	Running post build plugin 'npm Cache Cleanup'
    18-Oct-2020 10:47:47	Running post build plugin 'Clover Results Collector'
    18-Oct-2020 10:47:47	Running post build plugin 'Docker Container Cleanup'
    18-Oct-2020 10:47:47	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR'
    18-Oct-2020 10:47:47	Finalising the build...
    18-Oct-2020 10:47:47	Stopping timer.
    18-Oct-2020 10:47:47	Build CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR-1 completed.
    18-Oct-2020 10:47:47	Running on server: post build plugin 'NCover Results Collector'
    18-Oct-2020 10:47:47	Running on server: post build plugin 'Build Hanging Detection Configuration'
    18-Oct-2020 10:47:47	Running on server: post build plugin 'Clover Delta Calculator'
    18-Oct-2020 10:47:47	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    18-Oct-2020 10:47:47	All post build plugins have finished
    18-Oct-2020 10:47:47	Generating build results summary...
    18-Oct-2020 10:47:47	Saving build results to disk...
    18-Oct-2020 10:47:47	Store variable context...
    18-Oct-2020 10:47:47	Indexing build results...
    18-Oct-2020 10:47:47	Finished building CQ-GLOBALCOMPONENTSSTYLE110-GLOBALCOMPONENTSSTYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
