### PR TITLE
Small fixups for some picoserver compilation errors

### PR DESCRIPTION
**Pull request by kent-mcleod**

### CODE REVIEW

**Comment by nomadeel** [comment]
Cool, thanks for this!

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
